Description: "This is the bootstrap stacks to create Index/Views for the contract tests."
Resources:
  IndexResource:
    Type: AWS::ResourceExplorer2::Index
    Properties:
      Type: "LOCAL"
  ViewResource:
    Type: AWS::ResourceExplorer2::View
    Properties:
      ViewName: "defaultViewAssociationView"
    DependsOn: IndexResource
  ViewResource2:
    Type: AWS::ResourceExplorer2::View
    Properties:
      ViewName: "defaultViewAssociationView2"
    DependsOn: IndexResource
Outputs:
  ViewArn:
    Value:
      Ref: ViewResource
    Export:
      Name: awsresourceexplorer2defaultviewassociationcto1
  ViewArn2:
    Value:
      Ref: ViewResource2
    Export:
      Name: awsresourceexplorer2defaultviewassociationcto2
